### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by sdc011** [jhhudso/installsrv#1]
How would you go about setting this up? I spoke with Zac and got a mySQL server going, as well as an apache webserver, what else is needed?

**Comment by jhhudso** [comment]
There are three separate sub-projects here. Which one are you trying to setup?

* There's configuration and code to install Ubuntu and setup a desktop.
Requirements: DHCP Server, Apache, TFTP Server, DNS Server, Mirror of all of 
Ubuntu 16.0.4 x86_64, apt-mirror, 

* There's PostgreSQL DB models of an PC inventory system along with python 
code to enable printing inventory information on an EPSON receipt printer.
Requirements: PostgreSQL Server, ESC/POS compliant printer, python escpos 
module

* There's HTML, CSS and PHP code to enable adding inventory items to an 
uniCenta oPOS MariaDB DB and print barcode to barcode printer via CUPS on 
server.
Requirements: uniCenta oPOS installed and its DB setup, MariaDB Server, 
Apache, PHP, PHP MariaDB and GD modules, CUPS, barcode printer
